### PR TITLE
update identification example

### PR DESCRIPTION
**Pull request by kashefy**
This replaces identification models that are no longer compatible with the AMLTTP id example models with new identification models trained on the DCASE13 dataset.

Prerequisite: TWOEARS/auditory-front-end#23, otherwise we run into TWOEARS/auditory-front-end#22. IT may also be affected by TWOEARS/main#2

### CODE REVIEW

**Comment by kashefy** [comment]
This PR resolves #10

**Comment by hagenw** [comment]
Thanks, it is now running again.

I have two remaining questions:

1) I get a warning at the beginning, that a annotation file is missing:
```Matlab
Warning: Download failed (url=https://dev.qu.tu-berlin.de/projects/twoears-getdata/repository/raw//sound_databases/IEEE_AASP/void/void07.wav.txt), trying alternative
database... 
> In db.downloadFile (line 43)
  In db.getFile (line 85)
  In IdEvalFrame.readOnOffAnnotations (line 121)
  In readAudioFiles (line 95)
  In makeTestSignal (line 15)
  In identify (line 12) 
Warning: Download also failed with alternative database
(url=https://dev.qu.tu-berlin.de/projects/twoears-database/repository/revisions/master/raw//sound_databases/IEEE_AASP/void/void07.wav.txt) 
> In IdEvalFrame.readOnOffAnnotations (line 123)
  In readAudioFiles (line 95)
  In makeTestSignal (line 15)
  In identify (line 12) 
Warning: label annotation file not found: sound_databases/IEEE_AASP/void/void07.wav.txt. Assuming no events. 
> In IdEvalFrame.readOnOffAnnotations (line 140)
  In readAudioFiles (line 95)
  In makeTestSignal (line 15)
  In identify (line 12) 
```

2) The performance seems to be worse compared to the old version, see http://docs.twoears.eu/en/latest/examples/identification/

Now we got:
```
Evaluate scores...

relative error of clearthroat identification model: 0.032969
relative error of keyboard identification model: 0.206940
relative error of knock identification model: 0.382348
relative error of phone identification model: 0.238168
relative error of speech identification model: 0.254455
relative error of switch identification model: 0.035526
```
which are larger for most of the classes. And knock for example is always around 40%, see
id_performance

**Comment by kashefy** [comment]
The sound files from the void class contain noise and don't come with annotation files. The warning is expected and since we never train a classifier to detect 'void' events, this is ok.

These are not our best models, but ones that were trained on this particular public dataset. It is possible to replace with better models. So this is only a demo of functionality and does not reflect what we are capable of in terms of performance.
@ivo--t and @hagenw, are you ok with this, or do you think we should replace with better models?

**Comment by hagenw** [comment]
I think is it fine as it is. The main purpose of the demo is to show how it works.
For me this is ready to merge.

**Comment by hagenw** [comment]
Regarding 1., maybe we could hide the warning. The binaural simulator has different verbose levels, but I'm not sure if this will also hide warnings regarding the database.

**Comment by kashefy** [comment]
`sim.Verbose = false;`

So I guess this doesn't affect the db warnings.

**Comment by ivo--t** [comment]
I will have a look into the performance. The models are trained multi-conditionally, i.e. not specialized for clean sounds. But maybe there's something else going on.

**Comment by ivo--t** [comment]
Oh, and well -- I just got it. Those models were trained with ambient (diffuse) sources. This decreases performance definitely when used with point sources.

**Comment by ivo--t** [comment]
We should train new models for this example...

**Comment by kashefy** [comment]
Can't we change the example to play diffuse sound instead of retraining?

**Comment by ivo--t** [comment]
Retraining is very quick (IEEE data is so small). I'm at it, using the identification-training example (with a few modifications I'll push, too).

**Comment by ivo--t** [comment]
PR #16 is online.

**Comment by hagenw** [comment]
Looks good, I merged your update.
I guess we have to update the text in the documentation for this example as well. I created an extra issue for this:
https://github.com/TWOEARS/documentation/issues/64

**Pull request merged**
